name: trigger gitlab at unibas

on: [push]
#on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

#  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    - name: trigger gitlab
      uses: appleboy/gitlab-ci-action@master
      with:
        url: "https://git.scicore.unibas.ch/j.piccinali/mirror_test"
        token: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
        debug: true
        project_id: 1866
