name: trigger gitlab at unibas

on: [push]
#on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

#  # Allows you to run this workflow manually from the Actions tab
# workflow_dispatch:

#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.

# {{{ appleboy/gitlab-ci-action
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     # - uses: actions/checkout@v2
#     - name: trigger gitlab
#       uses: appleboy/gitlab-ci-action@master
#       with:
#         host: "https://git.scicore.unibas.ch"
#         token: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }}
#         debug: true
#         project_id: 1866
#         ref: "main"
# }}}



# {{{ SvanBoxel/gitlab-mirror-and-ci-action
# name: Mirror and run GitLab CI
# on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v1
    - uses: actions/checkout@v2
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.scicore.unibas.ch/j.piccinali/mirror_test"
        # args: "https://gitlab.com/<namespace>/<repository>"
      env:
        GITLAB_HOSTNAME: "https://git.scicore.unibas.ch"
        GITLAB_USERNAME: "j.piccinali"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} 
        # <-- Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "<GitLab project ID>" 
        # <-- https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.GITLAB_UNIBAS_PIPELINE_TRIGGER_TOKEN }} 
        # <-- https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        # --------------------------------
        # GITLAB_HOSTNAME: "gitlab.com"
        # GITLAB_USERNAME: "svboxel"
        # GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} // Generate here: https://gitlab.com/profile/personal_access_tokens
        # GITLAB_PROJECT_ID: "<GitLab project ID>" // https://gitlab.com/<namespace>/<repository>/edit
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
# }}}
